/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Open ERP API
 * OpenAPI spec version: 1.0
 */
import type { UserPayload } from './userPayload';

export interface AuthPayload {
  accessToken: string;
  refreshToken: string;
  user: UserPayload;
}
