/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Open ERP API
 * OpenAPI spec version: 1.0
 */

export * from './authPayload';
export * from './createCustomerDto';
export * from './createOrderDto';
export * from './createOrderProductDto';
export * from './createProductDto';
export * from './loginInput';
export * from './updateCustomerDto';
export * from './updateOrderDto';
export * from './updateOrderProductDto';
export * from './updateProductDto';
export * from './userPayload';